const config = {
    PORT : process.env.PORT || 8080,
    FRONTEND_URL : process.env.FRONTEND_URL,
    MONGODB_URL : process.env.MONGODB_URL,
    REDIS_URL : process.env.REDIS_URL,
    REDIS_SESSION_BUFFER_MINUTES : Number(process.env.REDIS_SESSION_BUFFER_MINUTES || 10),
    SESSION_SWEEP_INTERVAL_SECONDS : Number(process.env.SESSION_SWEEP_INTERVAL_SECONDS || 30),
    NODEMAILER_MAIL : process.env.NODEMAILER_MAIL,
    NODEMAIL_APP_PASSWORD : process.env.NODEMAIL_APP_PASSWORD,
    JWT_TOKEN_SECRET : process.env.JWT_TOKEN_SECRET,
    JWT_TOKEN_SIGNUP_MAIL_SECRET : process.env.JWT_TOKEN_SIGNUP_MAIL_SECRET,
    JWT_RESET_PASSWORD_SECRET : process.env.JWT_RESET_PASSWORD_SECRET,
}

module.exports  = config;